### ISSUE TITLE
The VPN card widget expands to its maximum height

### ISSUE THREAD

**Issue by arma7x** [mudler/edgevpn-gui#2]
https://i.imgur.com/CrPDySf.png

OS: Lubuntu 18.04.6 LTS
GO Version: go1.17.7 linux/amd64

**Comment by mudler** [comment]
Hi! thanks for opening the issue!

That's actually a good point! did you find a solution for this?

**Comment by arma7x** [comment]
Yes, ```b := container.NewVScroll(container.NewVBox(grid))```
https://github.com/mudler/edgevpn-gui/blob/master/gui/dashboard.go#L164

**Comment by mudler** [comment]
> Yes, `b := container.NewVScroll(container.NewVBox(grid))` https://github.com/mudler/edgevpn-gui/blob/master/gui/dashboard.go#L164

Thanks!
